package com.goxpro.xpro.util;

public enum EJBProviderEnum {
	// OPENEJB_4_LOCAL, OPENEJB_4_REMOTE, JBOSS_7_LOCAL, JBOSS_7_REMOTE, TOMCAT_7_OPENEJB_4_LOCAL;
	OPENEJB_4_LOCAL, OPENEJB_4_REMOTE, TOMCAT_7_OPENEJB_4_LOCAL;
}
